// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuyortcqojlgzeunmajm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eW9ydGNxb2psZ3pldW5tYWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjgwODMsImV4cCI6MjA2ODIwNDA4M30.7YoxpmM0oZpJRpFdnaM3WpTLJ5YLTcjDmbmy_fy16RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});